name: Public Scheduler

on:
  schedule:
    - cron: '0 */5 * * *' 
  workflow_dispatch: 

jobs:
  trigger-private:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Private Repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/imran866565-debug/student-verifier-bot/dispatches \
            -d '{"event_type":"start-bot"}'
